name: Sanity Check
on: [pull_request]
jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: ./.github/actions/status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: list files
        run: |
          ls ${{ github.workspace }}
